#!/bin/bash

if [ $1 -lt $2 ];then
  lowest=$1
  highest=$2
else
  lowest=$2
  highest=$1
fi
total=0

while [ $lowest -le $highest ]
do
  total=$(($total + $lowest))
  lowest=$((lowest + 1))
done

echo $total
